name: Checks

on: 'push'

jobs:
  unit_test:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install --upgrade --upgrade-strategy eager -e .
      - name: Run tests
        run: |
          python -m pip install pytest
          python -m pytest
